services:
  - type: web
    name: lucky-api
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: pnpm install && pnpm run build
    startCommand: node --enable-source-maps ./dist/index.mjs
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: BAILEYS_AUTH_PATH
        value: /app/sessions
      - key: DATABASE_URL
        fromDatabase:
          name: lucky-db
          property: connectionString

databases:
  - name: lucky-db
    plan: free
    region: frankfurt
    databaseName: lucky
    user: lucky